# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Inch Pages
tagline:          "Let's talk about documentation"

inch_pages:
  project_yaml_url: "https://github.com/inch-pages/inch-pages.github.io/edit/master/_projects.yml"
  new_issue_url: "https://github.com/inch-pages/inch-pages.github.io/issues/new"
